// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/http/request.go
//
// Generated by this command:
//
//	mockgen -source=pkg/http/request.go -destination=pkg/http/mocks/mock_request.go -package=mock_http
//

// Package mock_http is a generated GoMock package.
package mock_http

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCredentialLocation is a mock of CredentialLocation interface.
type MockCredentialLocation struct {
	ctrl     *gomock.Controller
	recorder *MockCredentialLocationMockRecorder
	isgomock struct{}
}

// MockCredentialLocationMockRecorder is the mock recorder for MockCredentialLocation.
type MockCredentialLocationMockRecorder struct {
	mock *MockCredentialLocation
}

// NewMockCredentialLocation creates a new mock instance.
func NewMockCredentialLocation(ctrl *gomock.Controller) *MockCredentialLocation {
	mock := &MockCredentialLocation{ctrl: ctrl}
	mock.recorder = &MockCredentialLocationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCredentialLocation) EXPECT() *MockCredentialLocationMockRecorder {
	return m.recorder
}

// GetIdentifier mocks base method.
func (m *MockCredentialLocation) GetIdentifier() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIdentifier")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetIdentifier indicates an expected call of GetIdentifier.
func (mr *MockCredentialLocationMockRecorder) GetIdentifier() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIdentifier", reflect.TypeOf((*MockCredentialLocation)(nil).GetIdentifier))
}

// GetPlacement mocks base method.
func (m *MockCredentialLocation) GetPlacement() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlacement")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetPlacement indicates an expected call of GetPlacement.
func (mr *MockCredentialLocationMockRecorder) GetPlacement() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlacement", reflect.TypeOf((*MockCredentialLocation)(nil).GetPlacement))
}
