# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envoy/config/core/v3/base.proto

require 'google/protobuf'

require 'envoy/config/core/v3/address_pb'
require 'envoy/config/core/v3/backoff_pb'
require 'envoy/config/core/v3/http_uri_pb'
require 'envoy/type/v3/percent_pb'
require 'envoy/type/v3/semantic_version_pb'
require 'google/protobuf/any_pb'
require 'google/protobuf/duration_pb'
require 'google/protobuf/struct_pb'
require 'google/protobuf/wrappers_pb'
require 'udpa/annotations/migrate_pb'
require 'udpa/annotations/status_pb'
require 'udpa/annotations/versioning_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("envoy/config/core/v3/base.proto", :syntax => :proto3) do
    add_message "envoy.config.core.v3.Locality" do
      optional :region, :string, 1
      optional :zone, :string, 2
      optional :sub_zone, :string, 3
    end
    add_message "envoy.config.core.v3.BuildVersion" do
      optional :version, :message, 1, "envoy.type.v3.SemanticVersion"
      optional :metadata, :message, 2, "google.protobuf.Struct"
    end
    add_message "envoy.config.core.v3.Extension" do
      optional :name, :string, 1
      optional :category, :string, 2
      optional :type_descriptor, :string, 3
      optional :version, :message, 4, "envoy.config.core.v3.BuildVersion"
      optional :disabled, :bool, 5
    end
    add_message "envoy.config.core.v3.Node" do
      optional :id, :string, 1
      optional :cluster, :string, 2
      optional :metadata, :message, 3, "google.protobuf.Struct"
      optional :locality, :message, 4, "envoy.config.core.v3.Locality"
      optional :user_agent_name, :string, 6
      repeated :extensions, :message, 9, "envoy.config.core.v3.Extension"
      repeated :client_features, :string, 10
      repeated :listening_addresses, :message, 11, "envoy.config.core.v3.Address"
      oneof :user_agent_version_type do
        optional :user_agent_version, :string, 7
        optional :user_agent_build_version, :message, 8, "envoy.config.core.v3.BuildVersion"
      end
    end
    add_message "envoy.config.core.v3.Metadata" do
      map :filter_metadata, :string, :message, 1, "google.protobuf.Struct"
    end
    add_message "envoy.config.core.v3.RuntimeUInt32" do
      optional :default_value, :uint32, 2
      optional :runtime_key, :string, 3
    end
    add_message "envoy.config.core.v3.RuntimePercent" do
      optional :default_value, :message, 1, "envoy.type.v3.Percent"
      optional :runtime_key, :string, 2
    end
    add_message "envoy.config.core.v3.RuntimeDouble" do
      optional :default_value, :double, 1
      optional :runtime_key, :string, 2
    end
    add_message "envoy.config.core.v3.RuntimeFeatureFlag" do
      optional :default_value, :message, 1, "google.protobuf.BoolValue"
      optional :runtime_key, :string, 2
    end
    add_message "envoy.config.core.v3.HeaderValue" do
      optional :key, :string, 1
      optional :value, :string, 2
    end
    add_message "envoy.config.core.v3.HeaderValueOption" do
      optional :header, :message, 1, "envoy.config.core.v3.HeaderValue"
      optional :append, :message, 2, "google.protobuf.BoolValue"
    end
    add_message "envoy.config.core.v3.HeaderMap" do
      repeated :headers, :message, 1, "envoy.config.core.v3.HeaderValue"
    end
    add_message "envoy.config.core.v3.DataSource" do
      oneof :specifier do
        optional :filename, :string, 1
        optional :inline_bytes, :bytes, 2
        optional :inline_string, :string, 3
      end
    end
    add_message "envoy.config.core.v3.RetryPolicy" do
      optional :retry_back_off, :message, 1, "envoy.config.core.v3.BackoffStrategy"
      optional :num_retries, :message, 2, "google.protobuf.UInt32Value"
    end
    add_message "envoy.config.core.v3.RemoteDataSource" do
      optional :http_uri, :message, 1, "envoy.config.core.v3.HttpUri"
      optional :sha256, :string, 2
      optional :retry_policy, :message, 3, "envoy.config.core.v3.RetryPolicy"
    end
    add_message "envoy.config.core.v3.AsyncDataSource" do
      oneof :specifier do
        optional :local, :message, 1, "envoy.config.core.v3.DataSource"
        optional :remote, :message, 2, "envoy.config.core.v3.RemoteDataSource"
      end
    end
    add_message "envoy.config.core.v3.TransportSocket" do
      optional :name, :string, 1
      oneof :config_type do
        optional :typed_config, :message, 3, "google.protobuf.Any"
      end
    end
    add_message "envoy.config.core.v3.RuntimeFractionalPercent" do
      optional :default_value, :message, 1, "envoy.type.v3.FractionalPercent"
      optional :runtime_key, :string, 2
    end
    add_message "envoy.config.core.v3.ControlPlane" do
      optional :identifier, :string, 1
    end
    add_enum "envoy.config.core.v3.RoutingPriority" do
      value :DEFAULT, 0
      value :HIGH, 1
    end
    add_enum "envoy.config.core.v3.RequestMethod" do
      value :METHOD_UNSPECIFIED, 0
      value :GET, 1
      value :HEAD, 2
      value :POST, 3
      value :PUT, 4
      value :DELETE, 5
      value :CONNECT, 6
      value :OPTIONS, 7
      value :TRACE, 8
      value :PATCH, 9
    end
    add_enum "envoy.config.core.v3.TrafficDirection" do
      value :UNSPECIFIED, 0
      value :INBOUND, 1
      value :OUTBOUND, 2
    end
  end
end

module Envoy
  module Config
    module Core
      module V3
        Locality = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.config.core.v3.Locality").msgclass
        BuildVersion = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.config.core.v3.BuildVersion").msgclass
        Extension = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.config.core.v3.Extension").msgclass
        Node = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.config.core.v3.Node").msgclass
        Metadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.config.core.v3.Metadata").msgclass
        RuntimeUInt32 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.config.core.v3.RuntimeUInt32").msgclass
        RuntimePercent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.config.core.v3.RuntimePercent").msgclass
        RuntimeDouble = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.config.core.v3.RuntimeDouble").msgclass
        RuntimeFeatureFlag = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.config.core.v3.RuntimeFeatureFlag").msgclass
        HeaderValue = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.config.core.v3.HeaderValue").msgclass
        HeaderValueOption = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.config.core.v3.HeaderValueOption").msgclass
        HeaderMap = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.config.core.v3.HeaderMap").msgclass
        DataSource = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.config.core.v3.DataSource").msgclass
        RetryPolicy = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.config.core.v3.RetryPolicy").msgclass
        RemoteDataSource = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.config.core.v3.RemoteDataSource").msgclass
        AsyncDataSource = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.config.core.v3.AsyncDataSource").msgclass
        TransportSocket = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.config.core.v3.TransportSocket").msgclass
        RuntimeFractionalPercent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.config.core.v3.RuntimeFractionalPercent").msgclass
        ControlPlane = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.config.core.v3.ControlPlane").msgclass
        RoutingPriority = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.config.core.v3.RoutingPriority").enummodule
        RequestMethod = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.config.core.v3.RequestMethod").enummodule
        TrafficDirection = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.config.core.v3.TrafficDirection").enummodule
      end
    end
  end
end
