# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envoy/config/core/v3/socket_option.proto

require 'google/protobuf'

require 'udpa/annotations/status_pb'
require 'udpa/annotations/versioning_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("envoy/config/core/v3/socket_option.proto", :syntax => :proto3) do
    add_message "envoy.config.core.v3.SocketOption" do
      optional :description, :string, 1
      optional :level, :int64, 2
      optional :name, :int64, 3
      optional :state, :enum, 6, "envoy.config.core.v3.SocketOption.SocketState"
      oneof :value do
        optional :int_value, :int64, 4
        optional :buf_value, :bytes, 5
      end
    end
    add_enum "envoy.config.core.v3.SocketOption.SocketState" do
      value :STATE_PREBIND, 0
      value :STATE_BOUND, 1
      value :STATE_LISTENING, 2
    end
  end
end

module Envoy
  module Config
    module Core
      module V3
        SocketOption = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.config.core.v3.SocketOption").msgclass
        SocketOption::SocketState = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.config.core.v3.SocketOption.SocketState").enummodule
      end
    end
  end
end
