# permissions for end users to view authconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: viewer-role
rules:
- apiGroups:
  - authorino.3scale.net
  resources:
  - authconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authorino.3scale.net
  resources:
  - authconfigs/status
  verbs:
  - get
