# The following patch applies the default strategy to convert between versions of the CRD
# The conversion webhook service is managed by the Authorino Operator
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: authconfigs.authorino.kuadrant.io
  annotations:
    cert-manager.io/inject-ca-from: ${WEBHOOK_NAMESPACE}/authorino-webhook-server-cert
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          namespace: ${WEBHOOK_NAMESPACE}
          name: authorino-webhooks
          path: /convert
      conversionReviewVersions:
      - v1beta2
      - v1beta3
