# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envoy/service/auth/v3/external_auth.proto

require 'google/protobuf'

require 'envoy/config/core/v3/base_pb'
require 'envoy/service/auth/v3/attribute_context_pb'
require 'envoy/type/v3/http_status_pb'
require 'google/protobuf/struct_pb'
require 'google/rpc/status_pb'
require 'udpa/annotations/status_pb'
require 'udpa/annotations/versioning_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("envoy/service/auth/v3/external_auth.proto", :syntax => :proto3) do
    add_message "envoy.service.auth.v3.CheckRequest" do
      optional :attributes, :message, 1, "envoy.service.auth.v3.AttributeContext"
    end
    add_message "envoy.service.auth.v3.DeniedHttpResponse" do
      optional :status, :message, 1, "envoy.type.v3.HttpStatus"
      repeated :headers, :message, 2, "envoy.config.core.v3.HeaderValueOption"
      optional :body, :string, 3
    end
    add_message "envoy.service.auth.v3.OkHttpResponse" do
      repeated :headers, :message, 2, "envoy.config.core.v3.HeaderValueOption"
      repeated :headers_to_remove, :string, 5
      optional :dynamic_metadata, :message, 3, "google.protobuf.Struct"
    end
    add_message "envoy.service.auth.v3.CheckResponse" do
      optional :status, :message, 1, "google.rpc.Status"
      optional :dynamic_metadata, :message, 4, "google.protobuf.Struct"
      oneof :http_response do
        optional :denied_response, :message, 2, "envoy.service.auth.v3.DeniedHttpResponse"
        optional :ok_response, :message, 3, "envoy.service.auth.v3.OkHttpResponse"
      end
    end
  end
end

module Envoy
  module Service
    module Auth
      module V3
        CheckRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.service.auth.v3.CheckRequest").msgclass
        DeniedHttpResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.service.auth.v3.DeniedHttpResponse").msgclass
        OkHttpResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.service.auth.v3.OkHttpResponse").msgclass
        CheckResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.service.auth.v3.CheckResponse").msgclass
      end
    end
  end
end
