# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envoy/api/v2/core/http_uri.proto

require 'google/protobuf'

require 'google/protobuf/duration_pb'
require 'udpa/annotations/migrate_pb'
require 'udpa/annotations/status_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("envoy/api/v2/core/http_uri.proto", :syntax => :proto3) do
    add_message "envoy.api.v2.core.HttpUri" do
      optional :uri, :string, 1
      optional :timeout, :message, 3, "google.protobuf.Duration"
      oneof :http_upstream_type do
        optional :cluster, :string, 2
      end
    end
  end
end

module Envoy
  module Api
    module V2
      module Core
        HttpUri = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.api.v2.core.HttpUri").msgclass
      end
    end
  end
end
