# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: envoy/service/auth/v3/external_auth.proto for package 'envoy.service.auth.v3'

require 'grpc'
require 'envoy/service/auth/v3/external_auth_pb'

module Envoy
  module Service
    module Auth
      module V3
        module Authorization
          # [#protodoc-title: Authorization Service ]
          #
          # The authorization service request messages used by external authorization :ref:`network filter
          # <config_network_filters_ext_authz>` and :ref:`HTTP filter <config_http_filters_ext_authz>`.
          #
          # A generic interface for performing authorization check on incoming
          # requests to a networked service.
          class Service

            include GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'envoy.service.auth.v3.Authorization'

            # Performs authorization check based on the attributes associated with the
            # incoming request, and returns status `OK` or not `OK`.
            rpc :Check, ::Envoy::Service::Auth::V3::CheckRequest, ::Envoy::Service::Auth::V3::CheckResponse
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
