# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envoy/api/v2/core/backoff.proto

require 'google/protobuf'

require 'google/protobuf/duration_pb'
require 'udpa/annotations/migrate_pb'
require 'udpa/annotations/status_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("envoy/api/v2/core/backoff.proto", :syntax => :proto3) do
    add_message "envoy.api.v2.core.BackoffStrategy" do
      optional :base_interval, :message, 1, "google.protobuf.Duration"
      optional :max_interval, :message, 2, "google.protobuf.Duration"
    end
  end
end

module Envoy
  module Api
    module V2
      module Core
        BackoffStrategy = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.api.v2.core.BackoffStrategy").msgclass
      end
    end
  end
end
