# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envoy/api/v2/core/base.proto

require 'google/protobuf'

require 'envoy/api/v2/core/address_pb'
require 'envoy/api/v2/core/backoff_pb'
require 'envoy/api/v2/core/http_uri_pb'
require 'envoy/type/percent_pb'
require 'envoy/type/semantic_version_pb'
require 'google/protobuf/any_pb'
require 'google/protobuf/duration_pb'
require 'google/protobuf/struct_pb'
require 'google/protobuf/wrappers_pb'
require 'udpa/annotations/migrate_pb'
require 'udpa/annotations/status_pb'
require 'envoy/api/v2/core/socket_option_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("envoy/api/v2/core/base.proto", :syntax => :proto3) do
    add_message "envoy.api.v2.core.Locality" do
      optional :region, :string, 1
      optional :zone, :string, 2
      optional :sub_zone, :string, 3
    end
    add_message "envoy.api.v2.core.BuildVersion" do
      optional :version, :message, 1, "envoy.type.SemanticVersion"
      optional :metadata, :message, 2, "google.protobuf.Struct"
    end
    add_message "envoy.api.v2.core.Extension" do
      optional :name, :string, 1
      optional :category, :string, 2
      optional :type_descriptor, :string, 3
      optional :version, :message, 4, "envoy.api.v2.core.BuildVersion"
      optional :disabled, :bool, 5
    end
    add_message "envoy.api.v2.core.Node" do
      optional :id, :string, 1
      optional :cluster, :string, 2
      optional :metadata, :message, 3, "google.protobuf.Struct"
      optional :locality, :message, 4, "envoy.api.v2.core.Locality"
      optional :build_version, :string, 5
      optional :user_agent_name, :string, 6
      repeated :extensions, :message, 9, "envoy.api.v2.core.Extension"
      repeated :client_features, :string, 10
      repeated :listening_addresses, :message, 11, "envoy.api.v2.core.Address"
      oneof :user_agent_version_type do
        optional :user_agent_version, :string, 7
        optional :user_agent_build_version, :message, 8, "envoy.api.v2.core.BuildVersion"
      end
    end
    add_message "envoy.api.v2.core.Metadata" do
      map :filter_metadata, :string, :message, 1, "google.protobuf.Struct"
    end
    add_message "envoy.api.v2.core.RuntimeUInt32" do
      optional :default_value, :uint32, 2
      optional :runtime_key, :string, 3
    end
    add_message "envoy.api.v2.core.RuntimeDouble" do
      optional :default_value, :double, 1
      optional :runtime_key, :string, 2
    end
    add_message "envoy.api.v2.core.RuntimeFeatureFlag" do
      optional :default_value, :message, 1, "google.protobuf.BoolValue"
      optional :runtime_key, :string, 2
    end
    add_message "envoy.api.v2.core.HeaderValue" do
      optional :key, :string, 1
      optional :value, :string, 2
    end
    add_message "envoy.api.v2.core.HeaderValueOption" do
      optional :header, :message, 1, "envoy.api.v2.core.HeaderValue"
      optional :append, :message, 2, "google.protobuf.BoolValue"
    end
    add_message "envoy.api.v2.core.HeaderMap" do
      repeated :headers, :message, 1, "envoy.api.v2.core.HeaderValue"
    end
    add_message "envoy.api.v2.core.DataSource" do
      oneof :specifier do
        optional :filename, :string, 1
        optional :inline_bytes, :bytes, 2
        optional :inline_string, :string, 3
      end
    end
    add_message "envoy.api.v2.core.RetryPolicy" do
      optional :retry_back_off, :message, 1, "envoy.api.v2.core.BackoffStrategy"
      optional :num_retries, :message, 2, "google.protobuf.UInt32Value"
    end
    add_message "envoy.api.v2.core.RemoteDataSource" do
      optional :http_uri, :message, 1, "envoy.api.v2.core.HttpUri"
      optional :sha256, :string, 2
      optional :retry_policy, :message, 3, "envoy.api.v2.core.RetryPolicy"
    end
    add_message "envoy.api.v2.core.AsyncDataSource" do
      oneof :specifier do
        optional :local, :message, 1, "envoy.api.v2.core.DataSource"
        optional :remote, :message, 2, "envoy.api.v2.core.RemoteDataSource"
      end
    end
    add_message "envoy.api.v2.core.TransportSocket" do
      optional :name, :string, 1
      oneof :config_type do
        optional :config, :message, 2, "google.protobuf.Struct"
        optional :typed_config, :message, 3, "google.protobuf.Any"
      end
    end
    add_message "envoy.api.v2.core.RuntimeFractionalPercent" do
      optional :default_value, :message, 1, "envoy.type.FractionalPercent"
      optional :runtime_key, :string, 2
    end
    add_message "envoy.api.v2.core.ControlPlane" do
      optional :identifier, :string, 1
    end
    add_enum "envoy.api.v2.core.RoutingPriority" do
      value :DEFAULT, 0
      value :HIGH, 1
    end
    add_enum "envoy.api.v2.core.RequestMethod" do
      value :METHOD_UNSPECIFIED, 0
      value :GET, 1
      value :HEAD, 2
      value :POST, 3
      value :PUT, 4
      value :DELETE, 5
      value :CONNECT, 6
      value :OPTIONS, 7
      value :TRACE, 8
      value :PATCH, 9
    end
    add_enum "envoy.api.v2.core.TrafficDirection" do
      value :UNSPECIFIED, 0
      value :INBOUND, 1
      value :OUTBOUND, 2
    end
  end
end

module Envoy
  module Api
    module V2
      module Core
        Locality = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.api.v2.core.Locality").msgclass
        BuildVersion = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.api.v2.core.BuildVersion").msgclass
        Extension = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.api.v2.core.Extension").msgclass
        Node = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.api.v2.core.Node").msgclass
        Metadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.api.v2.core.Metadata").msgclass
        RuntimeUInt32 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.api.v2.core.RuntimeUInt32").msgclass
        RuntimeDouble = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.api.v2.core.RuntimeDouble").msgclass
        RuntimeFeatureFlag = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.api.v2.core.RuntimeFeatureFlag").msgclass
        HeaderValue = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.api.v2.core.HeaderValue").msgclass
        HeaderValueOption = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.api.v2.core.HeaderValueOption").msgclass
        HeaderMap = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.api.v2.core.HeaderMap").msgclass
        DataSource = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.api.v2.core.DataSource").msgclass
        RetryPolicy = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.api.v2.core.RetryPolicy").msgclass
        RemoteDataSource = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.api.v2.core.RemoteDataSource").msgclass
        AsyncDataSource = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.api.v2.core.AsyncDataSource").msgclass
        TransportSocket = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.api.v2.core.TransportSocket").msgclass
        RuntimeFractionalPercent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.api.v2.core.RuntimeFractionalPercent").msgclass
        ControlPlane = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.api.v2.core.ControlPlane").msgclass
        RoutingPriority = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.api.v2.core.RoutingPriority").enummodule
        RequestMethod = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.api.v2.core.RequestMethod").enummodule
        TrafficDirection = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.api.v2.core.TrafficDirection").enummodule
      end
    end
  end
end
