//go:build !ignore_autogenerated

/*
Copyright 2020 Red Hat, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta3

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnonymousAccessSpec) DeepCopyInto(out *AnonymousAccessSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnonymousAccessSpec.
func (in *AnonymousAccessSpec) DeepCopy() *AnonymousAccessSpec {
	if in == nil {
		return nil
	}
	out := new(AnonymousAccessSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApiKeyAuthenticationSpec) DeepCopyInto(out *ApiKeyAuthenticationSpec) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.KeySelectors != nil {
		in, out := &in.KeySelectors, &out.KeySelectors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApiKeyAuthenticationSpec.
func (in *ApiKeyAuthenticationSpec) DeepCopy() *ApiKeyAuthenticationSpec {
	if in == nil {
		return nil
	}
	out := new(ApiKeyAuthenticationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthConfig) DeepCopyInto(out *AuthConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthConfig.
func (in *AuthConfig) DeepCopy() *AuthConfig {
	if in == nil {
		return nil
	}
	out := new(AuthConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AuthConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthConfigList) DeepCopyInto(out *AuthConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make(AuthConfigs, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthConfigList.
func (in *AuthConfigList) DeepCopy() *AuthConfigList {
	if in == nil {
		return nil
	}
	out := new(AuthConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AuthConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthConfigSpec) DeepCopyInto(out *AuthConfigSpec) {
	*out = *in
	if in.Hosts != nil {
		in, out := &in.Hosts, &out.Hosts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NamedPatterns != nil {
		in, out := &in.NamedPatterns, &out.NamedPatterns
		*out = make(map[string]PatternExpressions, len(*in))
		for key, val := range *in {
			var outVal []PatternExpression
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(PatternExpressions, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]PatternExpressionOrRef, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Authentication != nil {
		in, out := &in.Authentication, &out.Authentication
		*out = make(map[string]AuthenticationSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]MetadataSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Authorization != nil {
		in, out := &in.Authorization, &out.Authorization
		*out = make(map[string]AuthorizationSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Response != nil {
		in, out := &in.Response, &out.Response
		*out = new(ResponseSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Callbacks != nil {
		in, out := &in.Callbacks, &out.Callbacks
		*out = make(map[string]CallbackSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthConfigSpec.
func (in *AuthConfigSpec) DeepCopy() *AuthConfigSpec {
	if in == nil {
		return nil
	}
	out := new(AuthConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthConfigStatus) DeepCopyInto(out *AuthConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]AuthConfigStatusCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Summary.DeepCopyInto(&out.Summary)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthConfigStatus.
func (in *AuthConfigStatus) DeepCopy() *AuthConfigStatus {
	if in == nil {
		return nil
	}
	out := new(AuthConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthConfigStatusCondition) DeepCopyInto(out *AuthConfigStatusCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	if in.LastUpdatedTime != nil {
		in, out := &in.LastUpdatedTime, &out.LastUpdatedTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthConfigStatusCondition.
func (in *AuthConfigStatusCondition) DeepCopy() *AuthConfigStatusCondition {
	if in == nil {
		return nil
	}
	out := new(AuthConfigStatusCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthConfigStatusSummary) DeepCopyInto(out *AuthConfigStatusSummary) {
	*out = *in
	if in.HostsReady != nil {
		in, out := &in.HostsReady, &out.HostsReady
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthConfigStatusSummary.
func (in *AuthConfigStatusSummary) DeepCopy() *AuthConfigStatusSummary {
	if in == nil {
		return nil
	}
	out := new(AuthConfigStatusSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in AuthConfigs) DeepCopyInto(out *AuthConfigs) {
	{
		in := &in
		*out = make(AuthConfigs, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthConfigs.
func (in AuthConfigs) DeepCopy() AuthConfigs {
	if in == nil {
		return nil
	}
	out := new(AuthConfigs)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthResponseMethodSpec) DeepCopyInto(out *AuthResponseMethodSpec) {
	*out = *in
	if in.Plain != nil {
		in, out := &in.Plain, &out.Plain
		*out = new(PlainAuthResponseSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Json != nil {
		in, out := &in.Json, &out.Json
		*out = new(JsonAuthResponseSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Wristband != nil {
		in, out := &in.Wristband, &out.Wristband
		*out = new(WristbandAuthResponseSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthResponseMethodSpec.
func (in *AuthResponseMethodSpec) DeepCopy() *AuthResponseMethodSpec {
	if in == nil {
		return nil
	}
	out := new(AuthResponseMethodSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthenticationMethodSpec) DeepCopyInto(out *AuthenticationMethodSpec) {
	*out = *in
	if in.ApiKey != nil {
		in, out := &in.ApiKey, &out.ApiKey
		*out = new(ApiKeyAuthenticationSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Jwt != nil {
		in, out := &in.Jwt, &out.Jwt
		*out = new(JwtAuthenticationSpec)
		**out = **in
	}
	if in.OAuth2TokenIntrospection != nil {
		in, out := &in.OAuth2TokenIntrospection, &out.OAuth2TokenIntrospection
		*out = new(OAuth2TokenIntrospectionSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.KubernetesTokenReview != nil {
		in, out := &in.KubernetesTokenReview, &out.KubernetesTokenReview
		*out = new(KubernetesTokenReviewSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.X509ClientCertificate != nil {
		in, out := &in.X509ClientCertificate, &out.X509ClientCertificate
		*out = new(X509ClientCertificateAuthenticationSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Plain != nil {
		in, out := &in.Plain, &out.Plain
		*out = new(PlainIdentitySpec)
		**out = **in
	}
	if in.AnonymousAccess != nil {
		in, out := &in.AnonymousAccess, &out.AnonymousAccess
		*out = new(AnonymousAccessSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthenticationMethodSpec.
func (in *AuthenticationMethodSpec) DeepCopy() *AuthenticationMethodSpec {
	if in == nil {
		return nil
	}
	out := new(AuthenticationMethodSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthenticationSpec) DeepCopyInto(out *AuthenticationSpec) {
	*out = *in
	in.CommonEvaluatorSpec.DeepCopyInto(&out.CommonEvaluatorSpec)
	in.Credentials.DeepCopyInto(&out.Credentials)
	if in.Overrides != nil {
		in, out := &in.Overrides, &out.Overrides
		*out = make(ExtendedProperties, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Defaults != nil {
		in, out := &in.Defaults, &out.Defaults
		*out = make(ExtendedProperties, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	in.AuthenticationMethodSpec.DeepCopyInto(&out.AuthenticationMethodSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthenticationSpec.
func (in *AuthenticationSpec) DeepCopy() *AuthenticationSpec {
	if in == nil {
		return nil
	}
	out := new(AuthenticationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizationMethodSpec) DeepCopyInto(out *AuthorizationMethodSpec) {
	*out = *in
	if in.PatternMatching != nil {
		in, out := &in.PatternMatching, &out.PatternMatching
		*out = new(PatternMatchingAuthorizationSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Opa != nil {
		in, out := &in.Opa, &out.Opa
		*out = new(OpaAuthorizationSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.KubernetesSubjectAccessReview != nil {
		in, out := &in.KubernetesSubjectAccessReview, &out.KubernetesSubjectAccessReview
		*out = new(KubernetesSubjectAccessReviewAuthorizationSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.SpiceDB != nil {
		in, out := &in.SpiceDB, &out.SpiceDB
		*out = new(SpiceDBAuthorizationSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizationMethodSpec.
func (in *AuthorizationMethodSpec) DeepCopy() *AuthorizationMethodSpec {
	if in == nil {
		return nil
	}
	out := new(AuthorizationMethodSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizationSpec) DeepCopyInto(out *AuthorizationSpec) {
	*out = *in
	in.CommonEvaluatorSpec.DeepCopyInto(&out.CommonEvaluatorSpec)
	in.AuthorizationMethodSpec.DeepCopyInto(&out.AuthorizationMethodSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizationSpec.
func (in *AuthorizationSpec) DeepCopy() *AuthorizationSpec {
	if in == nil {
		return nil
	}
	out := new(AuthorizationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CallbackMethodSpec) DeepCopyInto(out *CallbackMethodSpec) {
	*out = *in
	if in.Http != nil {
		in, out := &in.Http, &out.Http
		*out = new(HttpEndpointSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CallbackMethodSpec.
func (in *CallbackMethodSpec) DeepCopy() *CallbackMethodSpec {
	if in == nil {
		return nil
	}
	out := new(CallbackMethodSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CallbackSpec) DeepCopyInto(out *CallbackSpec) {
	*out = *in
	in.CommonEvaluatorSpec.DeepCopyInto(&out.CommonEvaluatorSpec)
	in.CallbackMethodSpec.DeepCopyInto(&out.CallbackMethodSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CallbackSpec.
func (in *CallbackSpec) DeepCopy() *CallbackSpec {
	if in == nil {
		return nil
	}
	out := new(CallbackSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CelPredicate) DeepCopyInto(out *CelPredicate) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CelPredicate.
func (in *CelPredicate) DeepCopy() *CelPredicate {
	if in == nil {
		return nil
	}
	out := new(CelPredicate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonEvaluatorSpec) DeepCopyInto(out *CommonEvaluatorSpec) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]PatternExpressionOrRef, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Cache != nil {
		in, out := &in.Cache, &out.Cache
		*out = new(EvaluatorCaching)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonEvaluatorSpec.
func (in *CommonEvaluatorSpec) DeepCopy() *CommonEvaluatorSpec {
	if in == nil {
		return nil
	}
	out := new(CommonEvaluatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Credentials) DeepCopyInto(out *Credentials) {
	*out = *in
	if in.AuthorizationHeader != nil {
		in, out := &in.AuthorizationHeader, &out.AuthorizationHeader
		*out = new(Prefixed)
		**out = **in
	}
	if in.CustomHeader != nil {
		in, out := &in.CustomHeader, &out.CustomHeader
		*out = new(CustomHeader)
		**out = **in
	}
	if in.QueryString != nil {
		in, out := &in.QueryString, &out.QueryString
		*out = new(Named)
		**out = **in
	}
	if in.Cookie != nil {
		in, out := &in.Cookie, &out.Cookie
		*out = new(Named)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Credentials.
func (in *Credentials) DeepCopy() *Credentials {
	if in == nil {
		return nil
	}
	out := new(Credentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomHeader) DeepCopyInto(out *CustomHeader) {
	*out = *in
	out.Named = in.Named
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomHeader.
func (in *CustomHeader) DeepCopy() *CustomHeader {
	if in == nil {
		return nil
	}
	out := new(CustomHeader)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DenyWithSpec) DeepCopyInto(out *DenyWithSpec) {
	*out = *in
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(ValueOrSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(NamedValuesOrSelectors, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Body != nil {
		in, out := &in.Body, &out.Body
		*out = new(ValueOrSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DenyWithSpec.
func (in *DenyWithSpec) DeepCopy() *DenyWithSpec {
	if in == nil {
		return nil
	}
	out := new(DenyWithSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvaluatorCaching) DeepCopyInto(out *EvaluatorCaching) {
	*out = *in
	in.Key.DeepCopyInto(&out.Key)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvaluatorCaching.
func (in *EvaluatorCaching) DeepCopy() *EvaluatorCaching {
	if in == nil {
		return nil
	}
	out := new(EvaluatorCaching)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in ExtendedProperties) DeepCopyInto(out *ExtendedProperties) {
	{
		in := &in
		*out = make(ExtendedProperties, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtendedProperties.
func (in ExtendedProperties) DeepCopy() ExtendedProperties {
	if in == nil {
		return nil
	}
	out := new(ExtendedProperties)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalOpaPolicy) DeepCopyInto(out *ExternalOpaPolicy) {
	*out = *in
	if in.HttpEndpointSpec != nil {
		in, out := &in.HttpEndpointSpec, &out.HttpEndpointSpec
		*out = new(HttpEndpointSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalOpaPolicy.
func (in *ExternalOpaPolicy) DeepCopy() *ExternalOpaPolicy {
	if in == nil {
		return nil
	}
	out := new(ExternalOpaPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeaderSuccessResponseSpec) DeepCopyInto(out *HeaderSuccessResponseSpec) {
	*out = *in
	in.SuccessResponseSpec.DeepCopyInto(&out.SuccessResponseSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeaderSuccessResponseSpec.
func (in *HeaderSuccessResponseSpec) DeepCopy() *HeaderSuccessResponseSpec {
	if in == nil {
		return nil
	}
	out := new(HeaderSuccessResponseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HttpEndpointSpec) DeepCopyInto(out *HttpEndpointSpec) {
	*out = *in
	if in.Method != nil {
		in, out := &in.Method, &out.Method
		*out = new(HttpMethod)
		**out = **in
	}
	if in.Body != nil {
		in, out := &in.Body, &out.Body
		*out = new(ValueOrSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make(NamedValuesOrSelectors, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(NamedValuesOrSelectors, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.SharedSecret != nil {
		in, out := &in.SharedSecret, &out.SharedSecret
		*out = new(SecretKeyReference)
		**out = **in
	}
	if in.OAuth2 != nil {
		in, out := &in.OAuth2, &out.OAuth2
		*out = new(OAuth2ClientAuthentication)
		(*in).DeepCopyInto(*out)
	}
	in.Credentials.DeepCopyInto(&out.Credentials)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HttpEndpointSpec.
func (in *HttpEndpointSpec) DeepCopy() *HttpEndpointSpec {
	if in == nil {
		return nil
	}
	out := new(HttpEndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JsonAuthResponseSpec) DeepCopyInto(out *JsonAuthResponseSpec) {
	*out = *in
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(NamedValuesOrSelectors, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JsonAuthResponseSpec.
func (in *JsonAuthResponseSpec) DeepCopy() *JsonAuthResponseSpec {
	if in == nil {
		return nil
	}
	out := new(JsonAuthResponseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JwtAuthenticationSpec) DeepCopyInto(out *JwtAuthenticationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JwtAuthenticationSpec.
func (in *JwtAuthenticationSpec) DeepCopy() *JwtAuthenticationSpec {
	if in == nil {
		return nil
	}
	out := new(JwtAuthenticationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesSubjectAccessReviewAuthorizationSpec) DeepCopyInto(out *KubernetesSubjectAccessReviewAuthorizationSpec) {
	*out = *in
	if in.User != nil {
		in, out := &in.User, &out.User
		*out = new(ValueOrSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AuthorizationGroups != nil {
		in, out := &in.AuthorizationGroups, &out.AuthorizationGroups
		*out = new(ValueOrSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ResourceAttributes != nil {
		in, out := &in.ResourceAttributes, &out.ResourceAttributes
		*out = new(KubernetesSubjectAccessReviewResourceAttributesSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesSubjectAccessReviewAuthorizationSpec.
func (in *KubernetesSubjectAccessReviewAuthorizationSpec) DeepCopy() *KubernetesSubjectAccessReviewAuthorizationSpec {
	if in == nil {
		return nil
	}
	out := new(KubernetesSubjectAccessReviewAuthorizationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesSubjectAccessReviewResourceAttributesSpec) DeepCopyInto(out *KubernetesSubjectAccessReviewResourceAttributesSpec) {
	*out = *in
	in.Group.DeepCopyInto(&out.Group)
	in.Resource.DeepCopyInto(&out.Resource)
	in.SubResource.DeepCopyInto(&out.SubResource)
	in.Name.DeepCopyInto(&out.Name)
	in.Namespace.DeepCopyInto(&out.Namespace)
	in.Verb.DeepCopyInto(&out.Verb)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesSubjectAccessReviewResourceAttributesSpec.
func (in *KubernetesSubjectAccessReviewResourceAttributesSpec) DeepCopy() *KubernetesSubjectAccessReviewResourceAttributesSpec {
	if in == nil {
		return nil
	}
	out := new(KubernetesSubjectAccessReviewResourceAttributesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesTokenReviewSpec) DeepCopyInto(out *KubernetesTokenReviewSpec) {
	*out = *in
	if in.Audiences != nil {
		in, out := &in.Audiences, &out.Audiences
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesTokenReviewSpec.
func (in *KubernetesTokenReviewSpec) DeepCopy() *KubernetesTokenReviewSpec {
	if in == nil {
		return nil
	}
	out := new(KubernetesTokenReviewSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetadataMethodSpec) DeepCopyInto(out *MetadataMethodSpec) {
	*out = *in
	if in.Http != nil {
		in, out := &in.Http, &out.Http
		*out = new(HttpEndpointSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.UserInfo != nil {
		in, out := &in.UserInfo, &out.UserInfo
		*out = new(UserInfoMetadataSpec)
		**out = **in
	}
	if in.Uma != nil {
		in, out := &in.Uma, &out.Uma
		*out = new(UmaMetadataSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetadataMethodSpec.
func (in *MetadataMethodSpec) DeepCopy() *MetadataMethodSpec {
	if in == nil {
		return nil
	}
	out := new(MetadataMethodSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetadataSpec) DeepCopyInto(out *MetadataSpec) {
	*out = *in
	in.CommonEvaluatorSpec.DeepCopyInto(&out.CommonEvaluatorSpec)
	in.MetadataMethodSpec.DeepCopyInto(&out.MetadataMethodSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetadataSpec.
func (in *MetadataSpec) DeepCopy() *MetadataSpec {
	if in == nil {
		return nil
	}
	out := new(MetadataSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Named) DeepCopyInto(out *Named) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Named.
func (in *Named) DeepCopy() *Named {
	if in == nil {
		return nil
	}
	out := new(Named)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in NamedValuesOrSelectors) DeepCopyInto(out *NamedValuesOrSelectors) {
	{
		in := &in
		*out = make(NamedValuesOrSelectors, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamedValuesOrSelectors.
func (in NamedValuesOrSelectors) DeepCopy() NamedValuesOrSelectors {
	if in == nil {
		return nil
	}
	out := new(NamedValuesOrSelectors)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OAuth2ClientAuthentication) DeepCopyInto(out *OAuth2ClientAuthentication) {
	*out = *in
	out.ClientSecret = in.ClientSecret
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExtraParams != nil {
		in, out := &in.ExtraParams, &out.ExtraParams
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Cache != nil {
		in, out := &in.Cache, &out.Cache
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OAuth2ClientAuthentication.
func (in *OAuth2ClientAuthentication) DeepCopy() *OAuth2ClientAuthentication {
	if in == nil {
		return nil
	}
	out := new(OAuth2ClientAuthentication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OAuth2TokenIntrospectionSpec) DeepCopyInto(out *OAuth2TokenIntrospectionSpec) {
	*out = *in
	if in.Credentials != nil {
		in, out := &in.Credentials, &out.Credentials
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OAuth2TokenIntrospectionSpec.
func (in *OAuth2TokenIntrospectionSpec) DeepCopy() *OAuth2TokenIntrospectionSpec {
	if in == nil {
		return nil
	}
	out := new(OAuth2TokenIntrospectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpaAuthorizationSpec) DeepCopyInto(out *OpaAuthorizationSpec) {
	*out = *in
	if in.External != nil {
		in, out := &in.External, &out.External
		*out = new(ExternalOpaPolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpaAuthorizationSpec.
func (in *OpaAuthorizationSpec) DeepCopy() *OpaAuthorizationSpec {
	if in == nil {
		return nil
	}
	out := new(OpaAuthorizationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PatternExpression) DeepCopyInto(out *PatternExpression) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PatternExpression.
func (in *PatternExpression) DeepCopy() *PatternExpression {
	if in == nil {
		return nil
	}
	out := new(PatternExpression)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PatternExpressionOrRef) DeepCopyInto(out *PatternExpressionOrRef) {
	*out = *in
	out.PatternExpression = in.PatternExpression
	out.PatternRef = in.PatternRef
	out.CelPredicate = in.CelPredicate
	if in.All != nil {
		in, out := &in.All, &out.All
		*out = make([]UnstructuredPatternExpressionOrRef, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Any != nil {
		in, out := &in.Any, &out.Any
		*out = make([]UnstructuredPatternExpressionOrRef, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PatternExpressionOrRef.
func (in *PatternExpressionOrRef) DeepCopy() *PatternExpressionOrRef {
	if in == nil {
		return nil
	}
	out := new(PatternExpressionOrRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in PatternExpressions) DeepCopyInto(out *PatternExpressions) {
	{
		in := &in
		*out = make(PatternExpressions, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PatternExpressions.
func (in PatternExpressions) DeepCopy() PatternExpressions {
	if in == nil {
		return nil
	}
	out := new(PatternExpressions)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PatternMatchingAuthorizationSpec) DeepCopyInto(out *PatternMatchingAuthorizationSpec) {
	*out = *in
	if in.Patterns != nil {
		in, out := &in.Patterns, &out.Patterns
		*out = make([]PatternExpressionOrRef, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PatternMatchingAuthorizationSpec.
func (in *PatternMatchingAuthorizationSpec) DeepCopy() *PatternMatchingAuthorizationSpec {
	if in == nil {
		return nil
	}
	out := new(PatternMatchingAuthorizationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PatternRef) DeepCopyInto(out *PatternRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PatternRef.
func (in *PatternRef) DeepCopy() *PatternRef {
	if in == nil {
		return nil
	}
	out := new(PatternRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlainAuthResponseSpec) DeepCopyInto(out *PlainAuthResponseSpec) {
	*out = *in
	in.Value.DeepCopyInto(&out.Value)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlainAuthResponseSpec.
func (in *PlainAuthResponseSpec) DeepCopy() *PlainAuthResponseSpec {
	if in == nil {
		return nil
	}
	out := new(PlainAuthResponseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlainIdentitySpec) DeepCopyInto(out *PlainIdentitySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlainIdentitySpec.
func (in *PlainIdentitySpec) DeepCopy() *PlainIdentitySpec {
	if in == nil {
		return nil
	}
	out := new(PlainIdentitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Prefixed) DeepCopyInto(out *Prefixed) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Prefixed.
func (in *Prefixed) DeepCopy() *Prefixed {
	if in == nil {
		return nil
	}
	out := new(Prefixed)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResponseSpec) DeepCopyInto(out *ResponseSpec) {
	*out = *in
	if in.Unauthenticated != nil {
		in, out := &in.Unauthenticated, &out.Unauthenticated
		*out = new(DenyWithSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Unauthorized != nil {
		in, out := &in.Unauthorized, &out.Unauthorized
		*out = new(DenyWithSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Success.DeepCopyInto(&out.Success)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResponseSpec.
func (in *ResponseSpec) DeepCopy() *ResponseSpec {
	if in == nil {
		return nil
	}
	out := new(ResponseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyReference) DeepCopyInto(out *SecretKeyReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyReference.
func (in *SecretKeyReference) DeepCopy() *SecretKeyReference {
	if in == nil {
		return nil
	}
	out := new(SecretKeyReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpiceDBAuthorizationSpec) DeepCopyInto(out *SpiceDBAuthorizationSpec) {
	*out = *in
	if in.SharedSecret != nil {
		in, out := &in.SharedSecret, &out.SharedSecret
		*out = new(SecretKeyReference)
		**out = **in
	}
	if in.Subject != nil {
		in, out := &in.Subject, &out.Subject
		*out = new(SpiceDBObject)
		(*in).DeepCopyInto(*out)
	}
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = new(SpiceDBObject)
		(*in).DeepCopyInto(*out)
	}
	in.Permission.DeepCopyInto(&out.Permission)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpiceDBAuthorizationSpec.
func (in *SpiceDBAuthorizationSpec) DeepCopy() *SpiceDBAuthorizationSpec {
	if in == nil {
		return nil
	}
	out := new(SpiceDBAuthorizationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpiceDBObject) DeepCopyInto(out *SpiceDBObject) {
	*out = *in
	in.Name.DeepCopyInto(&out.Name)
	in.Kind.DeepCopyInto(&out.Kind)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpiceDBObject.
func (in *SpiceDBObject) DeepCopy() *SpiceDBObject {
	if in == nil {
		return nil
	}
	out := new(SpiceDBObject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SuccessResponseSpec) DeepCopyInto(out *SuccessResponseSpec) {
	*out = *in
	in.CommonEvaluatorSpec.DeepCopyInto(&out.CommonEvaluatorSpec)
	in.AuthResponseMethodSpec.DeepCopyInto(&out.AuthResponseMethodSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SuccessResponseSpec.
func (in *SuccessResponseSpec) DeepCopy() *SuccessResponseSpec {
	if in == nil {
		return nil
	}
	out := new(SuccessResponseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UmaMetadataSpec) DeepCopyInto(out *UmaMetadataSpec) {
	*out = *in
	if in.Credentials != nil {
		in, out := &in.Credentials, &out.Credentials
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UmaMetadataSpec.
func (in *UmaMetadataSpec) DeepCopy() *UmaMetadataSpec {
	if in == nil {
		return nil
	}
	out := new(UmaMetadataSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnstructuredPatternExpressionOrRef) DeepCopyInto(out *UnstructuredPatternExpressionOrRef) {
	*out = *in
	in.PatternExpressionOrRef.DeepCopyInto(&out.PatternExpressionOrRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnstructuredPatternExpressionOrRef.
func (in *UnstructuredPatternExpressionOrRef) DeepCopy() *UnstructuredPatternExpressionOrRef {
	if in == nil {
		return nil
	}
	out := new(UnstructuredPatternExpressionOrRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserInfoMetadataSpec) DeepCopyInto(out *UserInfoMetadataSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserInfoMetadataSpec.
func (in *UserInfoMetadataSpec) DeepCopy() *UserInfoMetadataSpec {
	if in == nil {
		return nil
	}
	out := new(UserInfoMetadataSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValueOrSelector) DeepCopyInto(out *ValueOrSelector) {
	*out = *in
	in.Value.DeepCopyInto(&out.Value)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValueOrSelector.
func (in *ValueOrSelector) DeepCopy() *ValueOrSelector {
	if in == nil {
		return nil
	}
	out := new(ValueOrSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WrappedSuccessResponseSpec) DeepCopyInto(out *WrappedSuccessResponseSpec) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]HeaderSuccessResponseSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.DynamicMetadata != nil {
		in, out := &in.DynamicMetadata, &out.DynamicMetadata
		*out = make(map[string]SuccessResponseSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WrappedSuccessResponseSpec.
func (in *WrappedSuccessResponseSpec) DeepCopy() *WrappedSuccessResponseSpec {
	if in == nil {
		return nil
	}
	out := new(WrappedSuccessResponseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WristbandAuthResponseSpec) DeepCopyInto(out *WristbandAuthResponseSpec) {
	*out = *in
	if in.CustomClaims != nil {
		in, out := &in.CustomClaims, &out.CustomClaims
		*out = make(NamedValuesOrSelectors, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.TokenDuration != nil {
		in, out := &in.TokenDuration, &out.TokenDuration
		*out = new(int64)
		**out = **in
	}
	if in.SigningKeyRefs != nil {
		in, out := &in.SigningKeyRefs, &out.SigningKeyRefs
		*out = make([]*WristbandSigningKeyRef, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(WristbandSigningKeyRef)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WristbandAuthResponseSpec.
func (in *WristbandAuthResponseSpec) DeepCopy() *WristbandAuthResponseSpec {
	if in == nil {
		return nil
	}
	out := new(WristbandAuthResponseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WristbandSigningKeyRef) DeepCopyInto(out *WristbandSigningKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WristbandSigningKeyRef.
func (in *WristbandSigningKeyRef) DeepCopy() *WristbandSigningKeyRef {
	if in == nil {
		return nil
	}
	out := new(WristbandSigningKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *X509ClientCertificateAuthenticationSpec) DeepCopyInto(out *X509ClientCertificateAuthenticationSpec) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new X509ClientCertificateAuthenticationSpec.
func (in *X509ClientCertificateAuthenticationSpec) DeepCopy() *X509ClientCertificateAuthenticationSpec {
	if in == nil {
		return nil
	}
	out := new(X509ClientCertificateAuthenticationSpec)
	in.DeepCopyInto(out)
	return out
}
