// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/auth/credentials.go
//
// Generated by this command:
//
//	mockgen -source=pkg/auth/credentials.go -destination=pkg/auth/mocks/mock_credentials.go
//

// Package mock_auth is a generated GoMock package.
package mock_auth

import (
	reflect "reflect"

	authv3 "github.com/envoyproxy/go-control-plane/envoy/service/auth/v3"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthCredentials is a mock of AuthCredentials interface.
type MockAuthCredentials struct {
	ctrl     *gomock.Controller
	recorder *MockAuthCredentialsMockRecorder
	isgomock struct{}
}

// MockAuthCredentialsMockRecorder is the mock recorder for MockAuthCredentials.
type MockAuthCredentialsMockRecorder struct {
	mock *MockAuthCredentials
}

// NewMockAuthCredentials creates a new mock instance.
func NewMockAuthCredentials(ctrl *gomock.Controller) *MockAuthCredentials {
	mock := &MockAuthCredentials{ctrl: ctrl}
	mock.recorder = &MockAuthCredentialsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthCredentials) EXPECT() *MockAuthCredentialsMockRecorder {
	return m.recorder
}

// GetCredentialsFromAuthReq mocks base method.
func (m *MockAuthCredentials) GetCredentialsFromAuthReq(arg0 *authv3.AttributeContext_HttpRequest) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCredentialsFromAuthReq", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCredentialsFromAuthReq indicates an expected call of GetCredentialsFromAuthReq.
func (mr *MockAuthCredentialsMockRecorder) GetCredentialsFromAuthReq(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCredentialsFromAuthReq", reflect.TypeOf((*MockAuthCredentials)(nil).GetCredentialsFromAuthReq), arg0)
}

// GetIdentifier mocks base method.
func (m *MockAuthCredentials) GetIdentifier() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIdentifier")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetIdentifier indicates an expected call of GetIdentifier.
func (mr *MockAuthCredentialsMockRecorder) GetIdentifier() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIdentifier", reflect.TypeOf((*MockAuthCredentials)(nil).GetIdentifier))
}

// GetPlacement mocks base method.
func (m *MockAuthCredentials) GetPlacement() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlacement")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetPlacement indicates an expected call of GetPlacement.
func (mr *MockAuthCredentialsMockRecorder) GetPlacement() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlacement", reflect.TypeOf((*MockAuthCredentials)(nil).GetPlacement))
}
