// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/common/auth_credentials/auth_credentials.go

// Package mock_auth_credentials is a generated GoMock package.
package mock_auth_credentials

import (
	reflect "reflect"

	envoy_service_auth_v3 "github.com/envoyproxy/go-control-plane/envoy/service/auth/v3"
	gomock "github.com/golang/mock/gomock"
)

// MockAuthCredentials is a mock of AuthCredentials interface.
type MockAuthCredentials struct {
	ctrl     *gomock.Controller
	recorder *MockAuthCredentialsMockRecorder
}

// MockAuthCredentialsMockRecorder is the mock recorder for MockAuthCredentials.
type MockAuthCredentialsMockRecorder struct {
	mock *MockAuthCredentials
}

// NewMockAuthCredentials creates a new mock instance.
func NewMockAuthCredentials(ctrl *gomock.Controller) *MockAuthCredentials {
	mock := &MockAuthCredentials{ctrl: ctrl}
	mock.recorder = &MockAuthCredentialsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthCredentials) EXPECT() *MockAuthCredentialsMockRecorder {
	return m.recorder
}

// GetCredentialsFromReq mocks base method.
func (m *MockAuthCredentials) GetCredentialsFromReq(arg0 *envoy_service_auth_v3.AttributeContext_HttpRequest) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCredentialsFromReq", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCredentialsFromReq indicates an expected call of GetCredentialsFromReq.
func (mr *MockAuthCredentialsMockRecorder) GetCredentialsFromReq(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCredentialsFromReq", reflect.TypeOf((*MockAuthCredentials)(nil).GetCredentialsFromReq), arg0)
}

// GetCredentialsKeySelector mocks base method.
func (m *MockAuthCredentials) GetCredentialsKeySelector() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCredentialsKeySelector")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetCredentialsKeySelector indicates an expected call of GetCredentialsKeySelector.
func (mr *MockAuthCredentialsMockRecorder) GetCredentialsKeySelector() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCredentialsKeySelector", reflect.TypeOf((*MockAuthCredentials)(nil).GetCredentialsKeySelector))
}
