# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envoy/config/core/v3/http_uri.proto

require 'google/protobuf'

require 'google/protobuf/duration_pb'
require 'udpa/annotations/status_pb'
require 'udpa/annotations/versioning_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("envoy/config/core/v3/http_uri.proto", :syntax => :proto3) do
    add_message "envoy.config.core.v3.HttpUri" do
      optional :uri, :string, 1
      optional :timeout, :message, 3, "google.protobuf.Duration"
      oneof :http_upstream_type do
        optional :cluster, :string, 2
      end
    end
  end
end

module Envoy
  module Config
    module Core
      module V3
        HttpUri = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.config.core.v3.HttpUri").msgclass
      end
    end
  end
end
