# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: udpa/annotations/versioning.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("udpa/annotations/versioning.proto", :syntax => :proto3) do
    add_message "udpa.annotations.VersioningAnnotation" do
      optional :previous_message_type, :string, 1
    end
  end
end

module Udpa
  module Annotations
    VersioningAnnotation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("udpa.annotations.VersioningAnnotation").msgclass
  end
end
