apiVersion: authorino.3scale.net/v1beta1
kind: AuthConfig
metadata:
  name: talker-api-protection
spec:
  hosts:
    - talker-api
  identity:
    - name: tier-1
      priority: 0
      apiKey:
        labelSelectors:
          tier: "1"
    - name: tier-2
      priority: 1
      apiKey:
        labelSelectors:
          tier: "2"
    - name: tier-3
      priority: 1
      apiKey:
        labelSelectors:
          tier: "3"
  metadata:
    - name: first
      http:
        endpoint: http://talker-api:3000
        method: GET
    - name: second
      priority: 1
      http:
        endpoint: http://talker-api:3000/first_uuid={auth.metadata.first.uuid}
        method: GET
  authorization:
    - name: allowed-endpoints
      json:
        conditions:
          - selector: context.request.http.path
            operator: neq
            value: /hi
          - selector: context.request.http.path
            operator: neq
            value: /hello
          - selector: context.request.http.path
            operator: neq
            value: /aloha
          - selector: context.request.http.path
            operator: neq
            value: /ciao
        rules:
          - selector: deny
            operator: eq
            value: "true"
    - name: more-expensive-policy # no point in evaluating this one if it's not an allowed endpoint
      priority: 1
      opa:
        inlineRego: |
          allow { true }
  response:
    - name: x-auth-data
      json:
        properties:
          - name: tier
            valueFrom:
              authJSON: auth.identity.metadata.labels.tier
          - name: first-uuid
            valueFrom:
              authJSON: auth.metadata.first.uuid
          - name: second-uuid
            valueFrom:
              authJSON: auth.metadata.second.uuid
          - name: second-path
            valueFrom:
              authJSON: auth.metadata.second.path
---
apiVersion: v1
kind: Secret
metadata:
  name: api-key-1
  labels:
    authorino.3scale.net/managed-by: authorino
    tier: "1"
stringData:
  api_key: ndyBzreUzF4zqDQsqSPMHkRhriEOtcRx
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: api-key-2
  labels:
    authorino.3scale.net/managed-by: authorino
    tier: "2"
stringData:
  api_key: K10Z4oi9kjziUYfh4Ed8f5cFRnRa7Iqg
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: api-key-3
  labels:
    authorino.3scale.net/managed-by: authorino
    tier: "3"
stringData:
  api_key: iu9ISOCMdOpDKov4eKNGSkhuZIuZC9Jj
type: Opaque
