# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envoy/type/v3/percent.proto

require 'google/protobuf'

require 'udpa/annotations/status_pb'
require 'udpa/annotations/versioning_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("envoy/type/v3/percent.proto", :syntax => :proto3) do
    add_message "envoy.type.v3.Percent" do
      optional :value, :double, 1
    end
    add_message "envoy.type.v3.FractionalPercent" do
      optional :numerator, :uint32, 1
      optional :denominator, :enum, 2, "envoy.type.v3.FractionalPercent.DenominatorType"
    end
    add_enum "envoy.type.v3.FractionalPercent.DenominatorType" do
      value :HUNDRED, 0
      value :TEN_THOUSAND, 1
      value :MILLION, 2
    end
  end
end

module Envoy
  module Type
    module V3
      Percent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.type.v3.Percent").msgclass
      FractionalPercent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.type.v3.FractionalPercent").msgclass
      FractionalPercent::DenominatorType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.type.v3.FractionalPercent.DenominatorType").enummodule
    end
  end
end
