# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envoy/type/v3/semantic_version.proto

require 'google/protobuf'

require 'udpa/annotations/status_pb'
require 'udpa/annotations/versioning_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("envoy/type/v3/semantic_version.proto", :syntax => :proto3) do
    add_message "envoy.type.v3.SemanticVersion" do
      optional :major_number, :uint32, 1
      optional :minor_number, :uint32, 2
      optional :patch, :uint32, 3
    end
  end
end

module Envoy
  module Type
    module V3
      SemanticVersion = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.type.v3.SemanticVersion").msgclass
    end
  end
end
