# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envoy/service/auth/v2/external_auth.proto

require 'google/protobuf'

require 'envoy/api/v2/core/base_pb'
require 'envoy/service/auth/v2/attribute_context_pb'
require 'envoy/type/http_status_pb'
require 'google/rpc/status_pb'
require 'udpa/annotations/status_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("envoy/service/auth/v2/external_auth.proto", :syntax => :proto3) do
    add_message "envoy.service.auth.v2.CheckRequest" do
      optional :attributes, :message, 1, "envoy.service.auth.v2.AttributeContext"
    end
    add_message "envoy.service.auth.v2.DeniedHttpResponse" do
      optional :status, :message, 1, "envoy.type.HttpStatus"
      repeated :headers, :message, 2, "envoy.api.v2.core.HeaderValueOption"
      optional :body, :string, 3
    end
    add_message "envoy.service.auth.v2.OkHttpResponse" do
      repeated :headers, :message, 2, "envoy.api.v2.core.HeaderValueOption"
    end
    add_message "envoy.service.auth.v2.CheckResponse" do
      optional :status, :message, 1, "google.rpc.Status"
      oneof :http_response do
        optional :denied_response, :message, 2, "envoy.service.auth.v2.DeniedHttpResponse"
        optional :ok_response, :message, 3, "envoy.service.auth.v2.OkHttpResponse"
      end
    end
  end
end

module Envoy
  module Service
    module Auth
      module V2
        CheckRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.service.auth.v2.CheckRequest").msgclass
        DeniedHttpResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.service.auth.v2.DeniedHttpResponse").msgclass
        OkHttpResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.service.auth.v2.OkHttpResponse").msgclass
        CheckResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.service.auth.v2.CheckResponse").msgclass
      end
    end
  end
end
