# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envoy/type/v3/http_status.proto

require 'google/protobuf'

require 'udpa/annotations/status_pb'
require 'udpa/annotations/versioning_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("envoy/type/v3/http_status.proto", :syntax => :proto3) do
    add_message "envoy.type.v3.HttpStatus" do
      optional :code, :enum, 1, "envoy.type.v3.StatusCode"
    end
    add_enum "envoy.type.v3.StatusCode" do
      value :Empty, 0
      value :Continue, 100
      value :OK, 200
      value :Created, 201
      value :Accepted, 202
      value :NonAuthoritativeInformation, 203
      value :NoContent, 204
      value :ResetContent, 205
      value :PartialContent, 206
      value :MultiStatus, 207
      value :AlreadyReported, 208
      value :IMUsed, 226
      value :MultipleChoices, 300
      value :MovedPermanently, 301
      value :Found, 302
      value :SeeOther, 303
      value :NotModified, 304
      value :UseProxy, 305
      value :TemporaryRedirect, 307
      value :PermanentRedirect, 308
      value :BadRequest, 400
      value :Unauthorized, 401
      value :PaymentRequired, 402
      value :Forbidden, 403
      value :NotFound, 404
      value :MethodNotAllowed, 405
      value :NotAcceptable, 406
      value :ProxyAuthenticationRequired, 407
      value :RequestTimeout, 408
      value :Conflict, 409
      value :Gone, 410
      value :LengthRequired, 411
      value :PreconditionFailed, 412
      value :PayloadTooLarge, 413
      value :URITooLong, 414
      value :UnsupportedMediaType, 415
      value :RangeNotSatisfiable, 416
      value :ExpectationFailed, 417
      value :MisdirectedRequest, 421
      value :UnprocessableEntity, 422
      value :Locked, 423
      value :FailedDependency, 424
      value :UpgradeRequired, 426
      value :PreconditionRequired, 428
      value :TooManyRequests, 429
      value :RequestHeaderFieldsTooLarge, 431
      value :InternalServerError, 500
      value :NotImplemented, 501
      value :BadGateway, 502
      value :ServiceUnavailable, 503
      value :GatewayTimeout, 504
      value :HTTPVersionNotSupported, 505
      value :VariantAlsoNegotiates, 506
      value :InsufficientStorage, 507
      value :LoopDetected, 508
      value :NotExtended, 510
      value :NetworkAuthenticationRequired, 511
    end
  end
end

module Envoy
  module Type
    module V3
      HttpStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.type.v3.HttpStatus").msgclass
      StatusCode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.type.v3.StatusCode").enummodule
    end
  end
end
