name: Add issues to project

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

permissions:
  contents: read

jobs:
  add-to-project:
    name: Add issue to project
    # Only run jobs if the feature branch is in your repo (not in a fork)
    # OR
    # it is an issue
    if: github.event.pull_request.head.repo.full_name == github.repository || github.event.issue.number != ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@5afcf98fcd03f1c2f92c3c83f58ae24323cc57fd # ratchet:actions/add-to-project@v2.0.0
        with:
          project-url: https://github.com/orgs/Kuadrant/projects/18
          github-token: ${{ secrets.ADD_ISSUES_TOKEN }}
